ansible_python_interpreter: /usr/bin/python3

# Normal operations user (exists after provisioning)
ansible_user: semaphore-agent

# Bootstrap user for fresh hosts (must already exist on new boxes)
bootstrap_user: eddie

# Provisioning marker file (defines whether host is "done")
provision_marker_path: /etc/markers/provisioned

# Keys
semaphore_agent_authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDV4fxm2cfZ7Y2yic4MbIDYnugokmV5mNxh4ndsegFQoPiebm7kRt/iMycGo74TUAGPKJr5cIycIlqPfyV32+By9RfukOugeXOz1GRn5Y1LBV3aaHKW7sczO+eUILTnESCjSp/yMWBXy9eYf2WzM0b9xhhVSY8MN7oBzfpVASJGpmwqd1n8ozr9qkSYqn1cOT4VwvKFp502AtLP2J9hN3GkBU1pGa45diY84QiAo9Ctb64aiSPPYXHPd88bywVYPKaB1z0AQqSqCxF5f8GQso08eUEDm1n+GTyQs2ZEh+1RhQCZKNhIPNDEpg4RrF8nHd1m2jrgu5yxLQ/PnHHBt+24yLJ0wqlbtHLAlWBAK1gd+ervtvirp5BJdpxCG7iidUlfMvgefL5a6X/zjuJ//d1gci6+q49wstwX8PnSbTzQJmibVDRsqW2PU7IMZaCRwvZ/6q8q/B46qBmMF3LoUyCTgW9Hnhp3SIcxV2DO2uj6wCDfi0EsUcs5A/K7HHTEm98= semaphore-agent@samba-1"

eddie_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINt1KNkGPH+YPWl6qHX0PhbsevkEw8H1R86nOVV03k8Z"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF+zfnhEIwiI2u03QnRjghuAYFQRbdzqT1pXHWD69eaG"

# Baseline packages (Debian/Ubuntu)
baseline_apt_packages:
  - vim
  - curl
  - rsync
  - tree
  - lsb-release
