docker_prep_enabled: true

docker_agent_name: docker-agent
docker_agent_uid: 1101
docker_agent_gid: 1101
docker_agent_home: /var/lib/docker-agent
docker_agent_shell: /usr/sbin/nologin

docker_service_name: docker

# Komodo Vars
komodo_repo_url: "ssh://git@gitlab-ssh.eddiequinn.casa:2424/compose-files/komodo.git"
komodo_repo_dest: "/etc/komodo/repos/komodo"
komodo_repo_branch: "master"
komodo_deploy_script: "./deploy.sh"

komodo_repo_ssh_dir: "/etc/komodo/ssh"
komodo_repo_ssh_key_path: "/etc/komodo/ssh/id_ed25519"
komodo_repo_known_hosts_path: "/etc/komodo/ssh/known_hosts"
